from datetime import datetime
import os


def generate_report(target, whois_data, port_data, output_dir="reports"):
    """
    Generate a professional HTML report from scan results.
    Returns the path to the generated report file.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"{output_dir}/report_{target}_{timestamp}.html"
    os.makedirs(output_dir, exist_ok=True)

    # Build the port rows HTML
    port_rows = ""
    for p in port_data:
        port_rows += f"""
        <tr>
          <td class="port">{p['port']}/tcp</td>
          <td class="open">OPEN</td>
          <td>{p['service']}</td>
          <td class="banner">{p['banner']}</td>
        </tr>"""

    # Build nameservers list
    ns_list = ", ".join(whois_data.get("name_servers", []))

    # The full HTML report as a string
    html = f"""
<html>
<head>
<meta charset="UTF-8">
<title>Recon Report — {target}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ background:#0a0f1a; color:#8baabf; font-family:monospace; font-size:13px; }}
  .header {{ background:#0f1825; border-bottom:2px solid #00ffaa; padding:30px 40px; }}
  .header h1 {{ color:#00ffaa; font-size:24px; letter-spacing:2px; }}
  .header .meta {{ color:#5a7a95; margin-top:6px; font-size:11px; }}
  .wrap {{ max-width:900px; margin:30px auto; padding:0 30px; }}
  .card {{ background:#0f1825; border:1px solid #1a2640; border-radius:8px; padding:24px; margin-bottom:20px; }}
  .card h2 {{ color:#38bdf8; font-size:13px; letter-spacing:2px; margin-bottom:16px; padding-bottom:10px; border-bottom:1px solid #1a2640; }}
  .info-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:10px; }}
  .info-item .label {{ color:#5a7a95; font-size:11px; }}
  .info-item .value {{ color:#d0e8f8; margin-top:2px; }}
  table {{ width:100%; border-collapse:collapse; }}
  th {{ text-align:left; padding:10px 14px; background:#141e30; color:#38bdf8; font-size:11px; letter-spacing:1px; }}
  td {{ padding:10px 14px; border-bottom:1px solid #1a2640; }}
  td.port {{ color:#00ffaa; font-weight:bold; }}
  td.open {{ color:#22c55e; }}
  td.banner {{ color:#8baabf; font-size:11px; }}
  tr:hover {{ background:#141e30; }}
  .footer {{ text-align:center; padding:30px; color:#2a4060; font-size:11px; }}
</style>
</head>
<body>
<div class="header">
  <h1>NETWORK RECON REPORT</h1>
  <div class="meta">
    Target: {target} | IP: {whois_data.get('ip','N/A')} |
    Generated: {timestamp} | Open Ports: {len(port_data)}
  </div>
</div>

<div class="wrap">
  <div class="card">
    <h2>// WHOIS INFORMATION</h2>
    <div class="info-grid">
      <div class="info-item"><div class="label">TARGET</div><div class="value">{target}</div></div>
      <div class="info-item"><div class="label">IP ADDRESS</div><div class="value">{whois_data.get('ip','N/A')}</div></div>
      <div class="info-item"><div class="label">REGISTRAR</div><div class="value">{whois_data.get('registrar','N/A')}</div></div>
      <div class="info-item"><div class="label">ORGANIZATION</div><div class="value">{whois_data.get('org','N/A')}</div></div>
      <div class="info-item"><div class="label">COUNTRY</div><div class="value">{whois_data.get('country','N/A')}</div></div>
      <div class="info-item"><div class="label">CREATED</div><div class="value">{whois_data.get('creation_date','N/A')}</div></div>
      <div class="info-item"><div class="label">EXPIRES</div><div class="value">{whois_data.get('expiry_date','N/A')}</div></div>
      <div class="info-item"><div class="label">NAME SERVERS</div><div class="value">{ns_list}</div></div>
    </div>
  </div>

  <div class="card">
    <h2>// OPEN PORTS & SERVICES ({len(port_data)} found)</h2>
    <table>
      <tr><th>PORT</th><th>STATE</th><th>SERVICE</th><th>BANNER</th></tr>
      {port_rows}
    </table>
  </div>
</div>

<div class="footer">Generated by net-recon-toolkit | For authorized testing only</div>
</body></html>"""

    # Write report to file
    with open(filename, "w") as f:
        f.write(html)

    print(f"\n[✓] Report saved: {filename}")
    return filename